import "./bootstrap";
import '../css/app.css'

import { createApp, h } from "vue";
import { createInertiaApp } from "@inertiajs/vue3";
import { ZiggyVue } from '../../vendor/tightenco/ziggy'   // ← this line is critical

createInertiaApp({
    resolve: (name) => {
        const pages = import.meta.glob("./Pages/**/*.vue", { eager: true });
        return pages[`./Pages/${name}.vue`];
    },
    setup({ el, App, props, plugin }) {
        createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(ZiggyVue, Ziggy)          // ← pass Ziggy object here (generated by @routes)
            .mount(el);
    },
});
